-- تعطيل RLS على كل جداول البيانات
-- الأدمن مصادق عليه من التطبيق، ماله داعي
ALTER TABLE "Users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Offices" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "cars" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Favorites" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingRequests" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingRequestOffices" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingOffers" DISABLE ROW LEVEL SECURITY;
